### ISSUE TITLE
Migrate content from main website

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRefOnline#1184]
Using https://github.com/nuxt/content

ToDo's:
- [x] Readd redirects (as soon as https://github.com/unjs/nitro/discussions/420 is implemented): 
   - `/faq` > `https://docs.jabref.org/faq`
   - `/paypal` > either to `https://www.paypal.com/cgi-bin/webscr?item_name=JabRef+Bibliography+Manager&cmd=_donations&lc=US&currency_code=EUR&business=donations%40jabref.org` or to `/donations` (which then should contain the contents of https://github.com/JabRef/jabref/wiki/Donations/)
   - `/gsoc/xyz` > `/codeprojects/gsoc/xyz`
   - `/bluehat2022` > `/codeprojects/bluehat2022`
   - `/surveys/` > `/surveys/2015`
- [ ] #1467
- [x] Migrate color scheme (once this is settled "globally" for the jabref org?)
- [ ] #1723
- [x] Move content from blog

- [x] Migrate downloads.jabref.org as well, and correct deep os-specific download links such as downloads.jabref.org/win (probably by fetching the latest release from github and building the link using this info). Done in #1460.
- [ ] #1464
- [x] Fix contraction of navbar on smaller devices 
- [x] Consider changing font back to lato (lato bold for headers, lato light for text)
- [ ] #1465
- [x] https://github.com/JabRef/JabRefOnline/issues/1477

**Comment by koppor** [comment]
- [ ] Add RSS \
   ![grafik](https://user-images.githubusercontent.com/1366654/194778804-3c7361ef-571f-4547-8576-c219fc1dc26d.png)

**Comment by koppor** [comment]
We should try to keep our URLs stable, if possible --> https://www.w3.org/Provider/Style/URI

**Comment by tobiasdiez** [comment]
Everything done here, remaining points have their own issues.
