### ISSUE TITLE
Refine installation instructions

### ISSUE THREAD

**Issue by koppor** [JabRef/JabRefOnline#119]
I start postgres by using following command

    docker run --rm -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres

The .env file

    DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:5432/jabref?schema=public"

When connecting, I get following error:

   "message": "\nInvalid `prisma.user.findUnique()` invocation:\n\n\n  Database `jabref.public` does not exist on the database server at `localhost:5432`.",

The current documentation does not contain a hint how to create the database.

**Comment by tobiasdiez** [comment]
Does `yarn prisma:migrate:dev` work?

**Comment by koppor** [comment]
```
$ prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "jabref", schema "public" at "localhost:5432"

PostgreSQL database jabref created at localhost:5432
```

Partially. Now I get

    Uncaught TypeError: response.user is null

**Comment by tobiasdiez** [comment]
Nice. The typeerror is in index.vue? This is currently my playground and you can safely ignore this error for now.

**Comment by koppor** [comment]
I could not add any entry, not change any setting. I was thinking, I could create a test bibliographic entry.

**Comment by tobiasdiez** [comment]
It's at a very early stage, most of the UI still needs to be implemented. As of now the API for syncing with JabRef was the main focus. But you can use `yarn prisma:seed` to fill the database with some test data.
