### ISSUE TITLE
Broken link "developers"

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/JabRefOnline#1364]
Where: https://github.com/JabRef/JabRefOnline/blob/main/components/LandingPageGetInvolved.vue

The link:       href="https://github.com/JabRef/jabref/blob/master/DEVELOPERS"

**Comment by tobiasdiez** [comment]
Correct link is https://github.com/JabRef/jabref/blob/main/MAINTAINERS, but we can probably do better than linking to this (ugly) file and instead show the members of the core team in a small popup upon hover.
