### ISSUE TITLE
Fix reflect-metadata error when used with server-side rendering (or in tests)

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRefOnline#137]
Already reported but needs reproduction: https://github.com/nuxt/nuxt.js/issues/8372

Related: https://github.com/nuxt-community/nuxt-property-decorator/issues/55

**Comment by tobiasdiez** [comment]
I tried now for 3 hours to fix / reproduce this with no success. Let's wait for Nuxt 3 then!

**Comment by adinvadim** [comment]
https://github.com/nuxt-community/nuxt-property-decorator/issues/55#issuecomment-859924223
