### ISSUE TITLE
Add frontend ui tests

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRefOnline#165]
Vue testing library seems to be popular:
- https://testing-library.com/docs/
- https://github.com/testing-library/vue-testing-library
- Example project: https://www.reddit.com/r/vuejs/comments/nonnjh/looking_for_code_repos_using_vue_testing_library/
- Reuse storybook stories as tests: https://storybook.js.org/tutorials/intro-to-storybook/vue/en/composite-component/ (Unit tests with Jest)

I'm not completely sold by the idea of having UI tests...

> Notice as well that this test is quite brittle. It's possible that as the project matures, and the exact implementation of the Task changes --perhaps using a different classname--the test will fail, and need to be updated. This is not necessarily a problem, but rather an indication to be careful liberally using unit tests for UI. They're not easy to maintain. Instead rely on visual, snapshot, and visual regression (see testing chapter) tests where possible.

from the storybook docs

**Comment by Siedlerchr** [comment]
Cypress seems to be currently the state of the art

**Comment by tobiasdiez** [comment]
Let's try it with the visual snapshot tests of storybook, and if that doesn't suffice we can always add cypress or the like later.
