### ISSUE TITLE
CORS  for express

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/JabRefOnline#175]
Add CORS middleware for express to allow the WordPlugin to communicate with JabRefOnlne.
Default it is equivalent to Access-Control-Allow-Origin : * 
http://expressjs.com/en/resources/middleware/cors.html

**Comment by tobiasdiez** [comment]
For security reasons, I would like to keep CORS disabled or at least restrict it to only a few known origins.

See https://github.com/JabRef/JabRef-Word-Addin/issues/30 for more details on how to circumvent CORS problems for the addin.
