### ISSUE TITLE
Header does not render nicely on mobile

### ISSUE THREAD

**Issue by koppor** [JabRef/JabRefOnline#1975]
Version as of today:

![image](https://user-images.githubusercontent.com/1366654/234507399-90354a4f-da6b-43a0-9394-1f938b11e17c.png)

**Comment by tobiasdiez** [comment]
Can also reproduce on desktop (make screen small, reload page). Maybe related to https://github.com/vueuse/vueuse/issues/2655 (although we already use the `smaller*` method). Docs: https://vueuse.org/core/useBreakpoints/
