### ISSUE TITLE
Fastly error: unknown domain: jabref.org.

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/JabRefOnline#1976]
# How to reproduce:

1. Use Mozilla Firefox or Microsoft Edge
2. enter `jabref.org`, `http://jabref.org` or `https://jabref.org` into the address-bar

Result:

![image](https://user-images.githubusercontent.com/73715071/218538721-33ed11b0-61fc-4a7f-976f-6d3c9b14ef55.png)

# Workaround:

- `https://www.jabref.org`,
- `http://www.jabref.org` and
- `www.JabRef.org`

   work properly

**Comment by tobiasdiez** [comment]
Fixed now.

**Comment by ThiloteE** [comment]
Thank you Tobias. Can confirm :-)
