### ISSUE TITLE
Relink "News" to blog.jabref.org

### ISSUE THREAD

**Issue by koppor** [JabRef/JabRefOnline#1979]
https://staging.www.jabref.org/ as of today:

![image](https://user-images.githubusercontent.com/1366654/235359617-07c3e6d9-134e-45c9-bd9b-c95b509f7f50.png)

Click on "News" should open https://blog.jabref.org/ (and the old News removed from the repository)

**Comment by tobiasdiez** [comment]
This is fixed now.
