### ISSUE TITLE
Feature: Scroll to top

### ISSUE THREAD

**Issue by bilalmirza74** [JabRef/JabRefOnline#2260]
After reaching the footer, instead of scrolling back up by rotating the mouse wheel or swiping on mobile, we can simply click on the scroll-to-top button.

**Describe the solution you'd like**
Adding a Scroll to Top Button 

**Additional context**

![image](https://github.com/JabRef/jabref/assets/84387676/7b71b24d-3709-433e-bab7-338c5c8bad1d)

**Comment by Siedlerchr** [comment]
It got automatically redirected, the repo is JabRef/Jabref-Online

**Comment by koppor** [comment]
@bilalmirza74 Try do do it here. - The repo https://github.com/JabRef/JabRefOnline also hosts our web site. There should be some documentation in this repo - or self-explanating.

**Comment by koppor** [comment]
@bilalmirza74 Please not that the issue does not contain any scientific evidence for such a button. Evidence can be en empirical "study" on web pages offering that feature, papers describing it, or listing prominent web pages. Thus, it could be that the main maintainer of this repository will reject your PR. Nevertheless, it is a good excessive for contributing to other code and using GitHub.
