### ISSUE TITLE
Feature: Scroll to top

### ISSUE THREAD

**Issue by bilalmirza74** [JabRef/JabRefOnline#2261]
After reaching the footer, instead of scrolling back up by rotating the mouse wheel or swiping on mobile, we can simply click on the scroll-to-top button.

Describe the solution you'd like
Adding a Scroll to Top Button

Additional context

![Screenshot 2023-10-25 163616](https://github.com/JabRef/JabRefOnline/assets/84387676/33a3dc71-5898-4b77-b2e7-f977dffdd95f)

**Comment by tobiasdiez** [comment]
Thanks for your suggestion. But after reading https://ux.stackexchange.com/questions/20663/do-people-use-jump-to-top-of-page-links and similar discussions, I don't think we need this. The page is not that long that scrolling takes a considerable amount of time. But happy to hear that you would like to contribute: here are a few other good issues that need help: https://github.com/JabRef/JabRefOnline/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+good+first+issue%22
