### ISSUE TITLE
Decide how to handle person names

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRefOnline#313]
*Problem*: There are many different used to represent person names. See [this w3 article](https://www.w3.org/International/questions/qa-personal-names) for a detailed discussion and [IFLA - Names of persons](https://www.ifla.org/node/4953) for a comprehensive overview for each nation. A few examples:
- Iceland: `Björk Guðmundsdóttir` with "given" name `Björk` and "family" name `Guðmundsdóttir`, although the latter is more a description/patronymic than a proper family name (it means daughter of `Guðmundur`). People prefer to be called by their given name (Björk) or by the full name. Sorting is done by given name. Also an article written by Björk Guðmundsdóttir would be cited by an in-text citation of the form `Björk 2020` (and not `Guðmundsdóttir 2020`).
- China:  `毛泽东` (Mao Ze Dong) the family name is 毛 Mao. The given name is Dong. The middle character, 泽 Ze, is a generational name and is somewhat part of the given name, i.e. you would say "Mr Mao" and "I'm a good friend of Ze Dong". There is no space between the characters in the name.
- Spain: `María José Carreño Quiñones` where `Carreño Quiñones` are multiple family names, and `María José` multiple given names. There might be additional particles like `Carreño de Quiñones`.
- America: Often people prefer to have their middle name abbreviated, e.g. `John Q. Public` (This is however not common eg in the UK)
- Philippines: Abbreviate double-middle names with only one letter, e.g. `Maria D. Go` for `Maria Dela Cruz Go`.
- India: Sometimes includes further information in the name, e.g. Kogaddu Birappa Timappa Nair follows the order villageName-fathersName-givenName-lastName
- Vietnam: Names such as Nguyễn Tấn Dũng follow the order familyName-middleName-givenName. They are referred to using the given name, ie. Mr. Dũng, not Mr. Nguyễn.
- Netherlands: Last names with a van particle, like `van Beukering` should be sorted under B; but if the person is Belgian, sort it under V

Takeaways:
- We cannot take the "family" name to get an in-text citation (e.g. Iceland)
- We cannot take the initial letters from the middle name to get the initials (e.g. Philippines)
- There is no consistent way to sort last names without further information which particles should be included/omitted (e.g. Netherlands vs Belgium)

This should be confronted with the following requirements for citation:
- For the references, one usually needs the full name.
- Sometimes an abbreviated name (i.e. with initials) is required in the references by some styles.
- Need a way to consistently sort names. 
- For in-text citations one usually needs a short name.

Overview of existing solutions:
- [CSL](https://docs.citationstyles.org/en/stable/specification.html#names):
   - “family”: surname minus any particles and suffixes
   - “given”: given names, either full (“John Edward”) or initialized (“J. E.”)
   - “suffix”: name suffix, e.g. “Jr.” in “John Smith Jr.” and “III” in “Bill Gates III”
   -  “non-dropping-particle”: name particles that are not dropped when only the surname is shown (“de” in the Dutch surname “de Koning”) but which may be treated separately from the family name, e.g. for sorting
   - “dropping-particle”: name particles that are dropped when only the surname is shown (“van” in “Ludwig van Beethoven”, which becomes “Beethoven”)

- [biblatex](https://mirror.koddos.net/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf)
  - family: The family name(s), know as ‘last’ in BibTeX. If a name consists of a single part only (for example, ‘Aristotle’), this part will be treated as the family name.
  - given: The given name(s). Note that given names are referred to as the ‘first’ names in the BibTeX file format documentation.
  - prefix: Any name prefices, for example von, van, of, da, de, del, della, etc. Note that name prefices are referred to as the ‘von’ part of the name in the BibTeX file format documentation.
  - suffix: Any name suffices, for example Jr, Sr. Note that name suffices are referred to as the ‘Jr’ part of the name in the BibTeX file format documentation.
 
- [ORCID](https://github.com/ORCID/orcid-model/blob/master/src/main/resources/record_3.0/personal-details-3.0.xsd)
   - "given-names": The given name(s) of the researcher or contributor.
   - "family-name": The family (last) name of the researcher. This element is optional, because some cultures only use given names.
   - "credit-name": The full name of the researcher as they prefer it to appear.
- [Citation-file-format](https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionspersongiven-names)

**Comment by Siedlerchr** [comment]
To be consistent with JabRef I would suggest using the biblatex one.

**Comment by tobiasdiez** [comment]
Decision: use CSL

In the long-term I would like to move to a more inclusive standard instead of the western-focused first + last name format. However, this would require a huge effort and changes in all involved parties (Jabref Desktop, CSL, Biber, ...). So let's do this later.

We choose the CSL format since it contains more information (namely if a prefix is "dropping" or not) and there is lossless conversion from CSL to biblatex, while the opposite conversion biblatex > CSL needs additional info.
